#include "assets.h"
#include "graphics.h"
#include <cstdio>

Humanoid genHumanoid(Point p)
{
    //restraints to be included to make sure the object is within the window limits
	Humanoid h1;
	int x,y,r;

	//head
	h1.head.center.x = p.x;
	h1.head.center.y = p.y;
	h1.head.radius = 40;
    circle(h1.head.center.x , h1.head.center.y , h1.head.radius);

    x = h1.head.center.x;
	y = h1.head.center.y;
	r = h1.head.radius;

	//neck
    h1.neck.tL.x = x-(r/3);
    h1.neck.tL.y = y+r-4;
    h1.neck.bR.x = x+(r/3);
    h1.neck.bR.y = y+r+20-4;
    rectangle(h1.neck.tL.x, h1.neck.tL.y , h1.neck.bR.x , h1.neck.bR.y);

    //torso
    h1.torso.tL.x = x-r;
    h1.torso.tL.y = y+r+20-4;
    h1.torso.bR.x = x+r;
    h1.torso.bR.y = y+r+20+(2*r+20)-4;
    rectangle(h1.torso.tL.x , h1.torso.tL.y , h1.torso.bR.x , h1.torso.bR.y );

    //rHand;
	//lHand;
	//rLeg;
	//lLeg;

    return h1; // returning reference to the humanoid type object generated by the function

}

/*int main()
{
    initwindow(480,480);
    Humanoid h1;
    Point temp;
    printf(" enter x,y \n");
    scanf("%d%d",&temp.x,&temp.y);
    h1 = genHumanoid(temp);
	system("pause");
}*/